# Delo z matrikami (knjižnjica NumPy)

## Uvod v NumPy

V tem poglavju si bomo pogledali, kako uporabljamo knjižnjico Numpy.

Najprej bomo instalirali NumPy.

In [1]:
import numpy as np

Če želimo pogledati, katero verzijo imamo nameščeno napišemo ukaz:

In [2]:
np.__version__

'2.2.3'

## Na kratko o Jupyter notebook-u

Celice zaganjamo s kombinacijo tipk SHIFT+ENTER.

Če želiš preklapljati med Med Code in Markdown uporabi tipko Y oz M. Celica ne sme biti aktivna. Samo označena.

## Osnovne NumPy and Ndarrays (multidimensional array)

### 1D matrika

Generirajmo enostavno 1D matriko

In [7]:
a = np.array([1, 3, 5, 2, 4, 7, 9])
print(a)

[1 3 5 2 4 7 9]


Če želimo preveriti katerega tipa je a:

In [9]:
a.dtype
print(a.dtype)

int64


Prvi element pokličemo z ukazom:

In [11]:
a[0]
print(a[0])

1


Ustvarimo novo matriko b:

In [12]:
b = np.array([1, 2, 3, 4, 5, 6, 7])
print(b)

[1 2 3 4 5 6 7]


Na tretje mesto želimo vriniti število 99:

In [13]:
b[2] = 99
print(b)

[ 1  2 99  4  5  6  7]


Iz matrike b želimo vzeti samo prve tri elemente:

In [14]:
b1 = b[:3]  # ko je index 3, ga ne vzame več. Vzame samo i0,i1,i2
print(b1)

[ 1  2 99]


Iz matrike b želimo vzeti samo zadnje štiri elemente:

In [ ]:
b1 = b[3:]  # ko je index 3 ga vzame in vse do konca.
print(b1)

[4 5 6 7]


### 2D matrika

Generirajmo enostavno 2D matriko

In [18]:
d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Iz matrike želimo vzeti točno določen element (recimo iz druge vrstice in drugega stolpca):

In [20]:
e = d[1, 1]
print(e)

6


Če želimo vzeti samo prvo vrstico:

In [28]:
e1 = d[0, :]
print(e1)

[1 2 3 4]


Če želimo vzeti samo prvi stolpec:

In [29]:
e1 = d[:, 0]  # Z ":"" vzamemo vse vrstice, z 0 vzamemo vse iz prvega stolpca.
print(e1)

[1 5 9]


Sedaj želimo rezultat v stolpičnem zapisu:

In [30]:
e2 = d[:, 0].reshape(-1, 1)
print(e2)

[[1]
 [5]
 [9]]


Generirajmo novo matriko:

In [41]:
f = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
g = np.array([1, 2, 3])
print(f)
print(g)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3]


Preverimo, koliko imata matriki f in g dimenzijo (1D, 2D, ...) -> uporabimo ndarray.dim

In [42]:
# ndarray.ndim: the number of axes (dimensions) of the array.
print(f"f ndim: {f.ndim}, g ndim: {g.ndim}")

f ndim: 2, g ndim: 1


Preverimo, koliko imata matriki f in g vrstic in koliko stolpcev -> uporabimo ndarray.shape

In [44]:
# ndarray.shape: the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension.
print(f"f shape: {f.shape}, g shape: {g.shape}")

f shape: (3, 4), g shape: (3,)


Preverimo, koliko imata matriki f in g elementov -> uporabimo ndarray.size

In [46]:
# ndarray.size: the total number of elements of the array. This is equal to the product of the elements of shape.
print(f"f size: {f.size}, g size: {g.size}")

f size: 12, g size: 3


Preverimo, za kakšne tipe vrednosti v matrikah f in g gre -> uporabimo ndarray.dtype

In [49]:
# ndarray.dtype: an object describing the type of the elements in the array.
print(f"f dtype: {f.dtype}, g dtype: {g.dtype}")

f dtype: int64, g dtype: int64


Preverimo, koliko mest v pomnilniku zavzamejo posamezni elementi v matrikah f in g -> uporabimo ndarray.itemsize

In [50]:
# ndarray.itemsize: the size in bytes of each element of the array.
print(f"f itemsize: {f.itemsize}, g itemsize: {g.itemsize}")

f itemsize: 8, g itemsize: 8


Preverimo, na katerem mestu se v pomnilniku nahajata matriki f in g -> uporabimo ndarray.data

In [52]:
# ndarray.data: the buffer containing the actual elements of the array.
# Normally, we won't need to use this attribute because we will access the elements in an array using indexing facilities.
print(f"f data: {f.data}, g data: {g.data}")

f data: <memory at 0x000001B2ED1CEDC0>, g data: <memory at 0x000001B2ECE4CA00>


### Kako vnaprej definirati matriko

Želimo zgenerirati 1D matriko s štirimi ničlami:

In [54]:
h = np.zeros(4)
print(h)

[0. 0. 0. 0.]


Želimo zgenerirati 2D matriko s samimi ničlami:

In [56]:
hh = np.zeros((2, 3))
print(hh)

[[0. 0. 0.]
 [0. 0. 0.]]


Za kreiranje matrik z ničlami lahko uporabimo tudi ukaz np.empty(), ki je hitrejši od np.zeros():

In [57]:
hhh = np.empty(5)
print(hhh)

[0.00000000e+000 6.95262445e-310 4.94065646e-324             nan
 0.00000000e+000]


Če želimo generirati enke v matriki:

In [60]:
hhhh = np.ones([4, 4])
print(hhhh)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Geneririranje vektorjev s funkcijama arrange in linspace

Želimo zgenerirati vekto s števili od 2 do 8, s korakom 2:

In [62]:
i = np.arange(2, 9, 2)  # Moramo vpisati 9, ker devet ne šteje več zraven.
print(i)

[2 4 6 8]


Lahko generiramo tudi vektorje z decimalnimi števili:

In [63]:
ii = np.arange(1, 5, 0.2)
print(ii)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8]


Če bi uporabili metodo linspace:

In [70]:
iii = np.linspace(0, 6, num=11)  # Interval od 0 do 6 razdelimo na enake dele, ki jih omejuje 11 točk.
print(iii)

[0.  0.6 1.2 1.8 2.4 3.  3.6 4.2 4.8 5.4 6. ]


Še en primer uporabe linspace-a tukaj:

In [71]:
iii = np.linspace(0, 1, num=5)
print(iii)

[0.   0.25 0.5  0.75 1.  ]


### Računske operacije nad matrikami

Imamo dve matriki. To sta j in k:

In [75]:
j = np.array([[1, 2], [3, 4]])
print(j)

[[1 2]
 [3 4]]


In [76]:
k = np.array([[5, 6], [7, 8]])
print(k)

[[5 6]
 [7 8]]


Seštevanje matrik (+), Seštejemo istoležne elemente.

In [77]:
print(j + k)

[[ 6  8]
 [10 12]]


Odštevanje matrik (-), Odštejemo istoležne elemente.

In [78]:
print(j - k)

[[-4 -4]
 [-4 -4]]


Množenje matrik (*), Množimo istoležne elemente.

In [79]:
print(j * k)

[[ 5 12]
 [21 32]]


Deljenje matrik (:), Delimo istoležne elemente.

In [80]:
print(j / k)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Izračunajmo še vektorski produkt j x k:

In [82]:
print(j.dot(k))

[[19 22]
 [43 50]]


Drug način za vektorski produkt je še:

In [86]:
print(np.dot(j, k))

[[19 22]
 [43 50]]


Skalarni produkt pa izračunamo kot:

In [87]:
print(np.vdot(j, k))

70
